#!/bin/bash


############################
# SystemCtl Services Utils
############################
function service_is_active {
    local service_name
    service_name=${1}
    if [ "$(systemctl is-active "${service_name}")" == "active" ]; then
        return 0
    fi
    return 1
}

function start_service {
    local service_name=${1}
    if service_is_active "${service_name}"; then
        echo >&2 "🚀 Service ${service_name} is already active"
    else
        echo >&2 "👷  Start service ${service_name}"
        sudo systemctl start ${service_name}
        while true; do
            if service_is_active "${service_name}"; then
                break
            fi
            echo >&2 "⏰ Wait for service ${service_name} to start"
            sleep 1
        done
        echo >&2 "🚀 Service ${service_name} is now active"
    fi

    return 0
}
