#!/bin/bash

die() {
    log "$*" "error"
    # Exit script
    kill -INT $$
}

try() {
    local cmd_response
    cmd_response=${?:-0}

    [ "${cmd_response}" -eq 0 ]; die "Operation not permitted: $*"
}