#!/bin/bash

alias mirrorx='sudo reflector --age 6 --latest 20 --fastest 20 --threads 20 --sort rate --protocol https --save /etc/pacman.d/mirrorlist --country France,Germany,Netherlands,Switzerland,Finland && eos-rankmirrors'

