#!/bin/bash

# prevent using python 3.10
export CLOUDSDK_PYTHON=/usr/bin/python3.9


# The next line updates PATH for the Google Cloud SDK.
if [ -f '/home/gabriel/google-cloud-cli-418.0.0-linux-x86_64/google-cloud-sdk/path.bash.inc' ]; then . '/home/gabriel/google-cloud-cli-418.0.0-linux-x86_64/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/home/gabriel/google-cloud-cli-418.0.0-linux-x86_64/google-cloud-sdk/completion.bash.inc' ]; then . '/home/gabriel/google-cloud-cli-418.0.0-linux-x86_64/google-cloud-sdk/completion.bash.inc'; fi
