#!/bin/bash

GCLOUD_FOLDER_PATH="${HOME}/google-cloud-sdk/"

if [ -d "$GCLOUD_FOLDER_PATH" ];
then
    # prevent using python 3.10
    export CLOUDSDK_PYTHON=/usr/bin/python3.9

    alias gcloud="${HOME}/google-cloud-sdk/bin/gcloud"

    # The next line updates PATH for the Google Cloud SDK.
    if [ -f "${HOME}/google-cloud-sdk/path.bash.inc" ]; then . "${HOME}/google-cloud-sdk/path.bash.inc"; fi

    # The next line enables shell command completion for gcloud.
    if [ -f "${HOME}/google-cloud-sdk/completion.bash.inc" ]; then . "${HOME}/google-cloud-sdk/completion.bash.inc"; fi
else 
    echo "[INFO]Gcloud not found in ${GCLOUD_FOLDER_PATH}"
fi