#!/bin/bash


if ! command -v berglas &> /dev/null
then
    echo "[WARNING]berglas not found, cannot source PACKAGECLOUD_TOKEN"
else
    export PACKAGECLOUD_TOKEN=$(echo $(berglas access sm://ma-dev2/packagecloud-token#1))
fi


MA_INFRA_PATH="${HOME}/MA/MA-Infra/"
if [ -d "${MA_INFRA_PATH}" ];
then
    source ~/MA/MA-Infra/tools/gssh/gssh.sh
else 
    echo "[INFO]MA Infra Repo not found in ${MA_INFRA_PATH}"
fi
