#!/bin/bash

# Install
# $ yay -S cloudflare-warp-bin
# $ warp-cli registration new
# $ warp-cli teams-enroll aviv-group

function cfs {
    sudo systemctl start warp-svc
    warp-cli connect
}

function cfk {
    sudo systemctl stop warp-svc
} 