#!/bin/bash

# Install
# $ yay -S cloudflare-warp-bin
# $ sudo systemctl start warp-svc
# $ warp-cli registration new
# $ warp-cli teams-enroll aviv-group

current_dir=$(dirname $(realpath ${HOME}/.bashrc))
source "${current_dir}/tools/common"

CLOUDFLARE_SERVICE_NAME=warp-svc

function cfs {
    start_service${CLOUDFLARE_SERVICE_NAME}

    echo "⏰ Wait for Daemon ${CLOUDFLARE_SERVICE_NAME} to start"
    sleep 2

    echo "👧 Connect"
    warp-cli connect
}

function cfk {
    sudo systemctl stop ${CLOUDFLARE_SERVICE_NAME}
}