#!/bin/bash

function service_is_active {
    if [ $(systemctl is-active ${service_name}) == "active" ]; then
        return 0
    fi
    return 1
}

function start_service {
    local service_name=${1}
    if service_is_active "${service_name}"; then
        echo >&2 "🚀 Service ${service_name} is already active"
    else
        echo >&2 "👷  Start service ${service_name}"
        sudo systemctl start ${service_name}
        while true; do
            if service_is_active "${service_name}"; then
                break
            fi
            echo >&2 "⏰ Wait for service ${service_name} to start"
            sleep 1
        done
        echo >&2 "🚀 Service ${service_name} is now active"
    fi

    return 0
}


function string_is_in_file {
    local str=${1}
    local filepath=${2}

    echo >&2 "👓 check that '${str}' is in ${filepath}"
    if grep -Fxq "$str" ${filepath}
    then
        echo >&2 "✅ ${str} is in ${filepath}"
        return 0
    else
        return 1
    fi
}