#!/bin/bash

current_dir=$(dirname $(realpath ${HOME}/.bashrc))
source "${current_dir}/tools/common"
source "${current_dir}/tools/dns"

function nords {
    local country=${1:-netherlands}
    local nordvpn_group_name="nordvpn"
    local service_name="nordvpnd.service"

    if id -nG "${USER}" | grep -qw "${nordvpn_group_name}"; then
        echo >&2 "$USER belongs to ${nordvpn_group_name}"
    else
        echo >&2 "💥 $USER does not belong to ${nordvpn_group_name}"
        return 1
    fi

    echo >&2 "🚀 Start nordvpnd.service"
    start_service ${service_name}
    # required ?
    # sudo systemctl start systemd-resolved.service


    local account_cmd_response=$(nordvpn account)
    if [ "$account_cmd_response" == "You are not logged in." ]; then
        echo >&2 "😇 Login (${is_logged_in})"
        nordvpn login

        echo >&2 "Re-run this command when you are logged in"
        return 1
    fi

    echo >&2 "👻 Connect to ${country}"
    nordvpn connect ${country}

    echo >&2 "🔀 Use google DNS"
    set_dns "google"
}

function nordk {
    # echo >&2 "👋 Disconnect"
    # nordvpn disconnect

    echo >&2 "💀 Stop NordVPN service"
    sudo systemctl stop nordvpnd.service

    echo >&2 "🔀 Reset DNS to default"
    set_dns
}